package io.apicurio.datamodels.core.diff;

public enum DiffType {
    PATH_ADDED("PATH_ADDED"),
    PATH_REMOVED("PATH_REMOVED"),
    PATH_MODIFIED("PATH_MODIFIED"),
    PATH_VARIABLE_MODIFIED("PATH_VARIABLE_MODIFIED"),

    PATH_OPERATION_ADDED("PATH_OPERATION_ADDED"),
    PATH_OPERATION_REMOVED("PATH_OPERATION_REMOVED"),

    OPERATION_ID_ADDED("OPERATION_ID_ADDED"),
    OPERATION_ID_MODIFIED("OPERATION_ID_MODIFIED"),
    OPERATION_ID_REMOVED("OPERATION_ID_REMOVED"),

    REQUEST_BODY_ADDED("REQUEST_BODY_ADDED"),
    REQUEST_BODY_REMOVED("REQUEST_BODY_REMOVED"),

    REQUEST_BODY_MEDIA_TYPE_ADDED("REQUEST_BODY_MEDIA_TYPE_ADDED"),
    REQUEST_BODY_MEDIA_TYPE_REMOVED("REQUEST_BODY_MEDIA_TYPE_REMOVED"),

    REQUEST_BODY_TYPE_MODIFIED("REQUEST_BODY_TYPE_MODIFIED"),
    REQUEST_BODY_REQUIRED_FIELD_ADDED("REQUEST_BODY_REQUIRED_FIELD_ADDED"),
    REQUEST_BODY_REQUIRED_FIELD_REMOVED("REQUEST_BODY_REQUIRED_FIELD_REMOVED"),
    REQUEST_BODY_PROPERTY_ADDED("REQUEST_BODY_REQUIRED_PROPERTY_ADDED"),
    REQUEST_BODY_PROPERTY_REMOVED("REQUEST_BODY_REQUIRED_PROPERTY_ADDED"),
    REQUEST_BODY_PROPERTY_TYPE_MODIFIED("REQUEST_BODY_PROPERTY_TYPE_MODIFIED"),
    REQUEST_BODY_PROPERTY_FORMAT_ADDED("REQUEST_BODY_PROPERTY_FORMAT_ADDED"),
    REQUEST_BODY_PROPERTY_FORMAT_MODIFIED("REQUEST_BODY_PROPERTY_FORMAT_MODIFIED"),
    REQUEST_BODY_PROPERTY_FORMAT_REMOVED("REQUEST_BODY_PROPERTY_FORMAT_REMOVED"),
    ;

    private final String code;

    DiffType(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
